// Code generated by Axon framework. DO NOT EDIT.
// This file was automatically generated and should not be modified manually.

package controllers

import (
	"net/http"
	"strconv"
	"fmt"

	"github.com/labstack/echo/v4"
	"go.uber.org/fx"
	"github.com/toyz/axon/pkg/axon"
	"github.com/toyz/axon/examples/complete-app/internal/parsers"

	"github.com/toyz/axon/examples/complete-app/internal/services"
	"github.com/toyz/axon/examples/complete-app/internal/models"
	middleware "github.com/toyz/axon/examples/complete-app/internal/middleware"
)

type AuthMiddleware = middleware.AuthMiddleware
type LoggingMiddleware = middleware.LoggingMiddleware

func NewUserController(userService *services.UserService) *UserController {
	return &UserController{
		UserService: userService,
	}
}

func NewHealthController(databaseService *services.DatabaseService) *HealthController {
	return &HealthController{
		DatabaseService: databaseService,
	}
}

func NewProductController(databaseService *services.DatabaseService) *ProductController {
	return &ProductController{
		DatabaseService: databaseService,
	}
}

func NewSessionController(sessionFactory func() *services.SessionService, userService *services.UserService) *SessionController {
	return &SessionController{
		SessionFactory: sessionFactory,
		UserService: userService,
	}
}

func wrapUserControllerGetAllUsers(handler *UserController) echo.HandlerFunc {
	return func(c echo.Context) error {

		data, err := handler.GetAllUsers()
		if err != nil {
			return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
		}
		return c.JSON(http.StatusOK, data)
	}
}

func wrapUserControllerGetUser(handler *UserController) echo.HandlerFunc {
	return func(c echo.Context) error {
		id, err := strconv.Atoi(c.Param("id"))
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, "Invalid id: must be an integer")
		}

		var data interface{}
		data, err = handler.GetUser(id)
		if err != nil {
			return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
		}
		return c.JSON(http.StatusOK, data)
	}
}

func wrapUserControllerCreateUser(handler *UserController, authmiddleware *AuthMiddleware) echo.HandlerFunc {
	baseHandler := func(c echo.Context) error {
		var body models.CreateUserRequest
		if err := c.Bind(&body); err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, err.Error())
		}

		response, err := handler.CreateUser(body)
		if err != nil {
			return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
		}
		if response == nil {
			return echo.NewHTTPError(http.StatusInternalServerError, "handler returned nil response")
		}
		return c.JSON(response.StatusCode, response.Body)
	}

	// Apply middlewares in order
	finalHandler := baseHandler
	finalHandler = authmiddleware.Handle(finalHandler)

	return finalHandler
}

func wrapUserControllerUpdateUser(handler *UserController, authmiddleware *AuthMiddleware) echo.HandlerFunc {
	baseHandler := func(c echo.Context) error {
		id, err := strconv.Atoi(c.Param("id"))
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, "Invalid id: must be an integer")
		}
		var body models.UpdateUserRequest
		if err := c.Bind(&body); err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, err.Error())
		}

		var response *axon.Response
		response, err = handler.UpdateUser(id, body)
		if err != nil {
			return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
		}
		if response == nil {
			return echo.NewHTTPError(http.StatusInternalServerError, "handler returned nil response")
		}
		return c.JSON(response.StatusCode, response.Body)
	}

	// Apply middlewares in order
	finalHandler := baseHandler
	finalHandler = authmiddleware.Handle(finalHandler)

	return finalHandler
}

func wrapUserControllerDeleteUser(handler *UserController, authmiddleware *AuthMiddleware) echo.HandlerFunc {
	baseHandler := func(c echo.Context) error {
		id, err := strconv.Atoi(c.Param("id"))
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, "Invalid id: must be an integer")
		}

		err = handler.DeleteUser(c, id)
		if err != nil {
			return err
		}
		return nil
	}

	// Apply middlewares in order
	finalHandler := baseHandler
	finalHandler = authmiddleware.Handle(finalHandler)

	return finalHandler
}

func wrapHealthControllerGetHealth(handler *HealthController) echo.HandlerFunc {
	return func(c echo.Context) error {

		data, err := handler.GetHealth()
		if err != nil {
			return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
		}
		return c.JSON(http.StatusOK, data)
	}
}

func wrapHealthControllerGetReadiness(handler *HealthController) echo.HandlerFunc {
	return func(c echo.Context) error {

		data, err := handler.GetReadiness()
		if err != nil {
			return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
		}
		return c.JSON(http.StatusOK, data)
	}
}

func wrapProductControllerGetProduct(handler *ProductController) echo.HandlerFunc {
	return func(c echo.Context) error {
		id, err := axon.ParseUUID(c, c.Param("id"))
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, "Invalid id: must be a valid UUID")
		}

		var data interface{}
		data, err = handler.GetProduct(id)
		if err != nil {
			return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
		}
		return c.JSON(http.StatusOK, data)
	}
}

func wrapProductControllerGetProductByCode(handler *ProductController, loggingmiddleware *LoggingMiddleware) echo.HandlerFunc {
	baseHandler := func(c echo.Context) error {
		code, err := parsers.ParseProductCode(c, c.Param("code"))
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid code: %v", err))
		}

		var data interface{}
		data, err = handler.GetProductByCode(code)
		if err != nil {
			return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
		}
		return c.JSON(http.StatusOK, data)
	}

	// Apply middlewares in order
	finalHandler := baseHandler
	finalHandler = loggingmiddleware.Handle(finalHandler)

	return finalHandler
}

func wrapProductControllerGetProductSales(handler *ProductController, authmiddleware *AuthMiddleware, loggingmiddleware *LoggingMiddleware) echo.HandlerFunc {
	baseHandler := func(c echo.Context) error {
		dateRange, err := parsers.ParseDateRange(c, c.Param("dateRange"))
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid dateRange: %v", err))
		}

		var data interface{}
		data, err = handler.GetProductSales(dateRange)
		if err != nil {
			return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
		}
		return c.JSON(http.StatusOK, data)
	}

	// Apply middlewares in order
	finalHandler := baseHandler
	finalHandler = loggingmiddleware.Handle(finalHandler)
	finalHandler = authmiddleware.Handle(finalHandler)

	return finalHandler
}

func wrapProductControllerCreateProductInCategory(handler *ProductController, authmiddleware *AuthMiddleware) echo.HandlerFunc {
	baseHandler := func(c echo.Context) error {
		categoryId, err := axon.ParseUUID(c, c.Param("categoryId"))
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, "Invalid categoryId: must be a valid UUID")
		}
		var body models.CreateProductRequest
		if err := c.Bind(&body); err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, err.Error())
		}

		var data interface{}
		data, err = handler.CreateProductInCategory(c, categoryId, body)
		if err != nil {
			return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
		}
		return c.JSON(http.StatusOK, data)
	}

	// Apply middlewares in order
	finalHandler := baseHandler
	finalHandler = authmiddleware.Handle(finalHandler)

	return finalHandler
}

func wrapProductControllerUpdateProduct(handler *ProductController) echo.HandlerFunc {
	return func(c echo.Context) error {
		id, err := axon.ParseUUID(c, c.Param("id"))
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, "Invalid id: must be a valid UUID")
		}
		var body models.UpdateProductRequest
		if err := c.Bind(&body); err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, err.Error())
		}

		var data interface{}
		data, err = handler.UpdateProduct(id, body)
		if err != nil {
			return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
		}
		return c.JSON(http.StatusOK, data)
	}
}

func wrapProductControllerDeleteProduct(handler *ProductController) echo.HandlerFunc {
	return func(c echo.Context) error {
		id, err := axon.ParseUUID(c, c.Param("id"))
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, "Invalid id: must be a valid UUID")
		}

		err = handler.DeleteProduct(id)
		if err != nil {
			return err
		}
		return nil
	}
}

func wrapSessionControllerStartSession(handler *SessionController, loggingmiddleware *LoggingMiddleware) echo.HandlerFunc {
	baseHandler := func(c echo.Context) error {
		userID, err := strconv.Atoi(c.Param("userID"))
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, "Invalid userID: must be an integer")
		}

		var response *axon.Response
		response, err = handler.StartSession(userID)
		if err != nil {
			return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
		}
		if response == nil {
			return echo.NewHTTPError(http.StatusInternalServerError, "handler returned nil response")
		}
		return c.JSON(response.StatusCode, response.Body)
	}

	// Apply middlewares in order
	finalHandler := baseHandler
	finalHandler = loggingmiddleware.Handle(finalHandler)

	return finalHandler
}

func wrapSessionControllerGetSessionInfo(handler *SessionController, loggingmiddleware *LoggingMiddleware) echo.HandlerFunc {
	baseHandler := func(c echo.Context) error {
		userID, err := strconv.Atoi(c.Param("userID"))
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, "Invalid userID: must be an integer")
		}

		var data interface{}
		data, err = handler.GetSessionInfo(userID)
		if err != nil {
			return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
		}
		return c.JSON(http.StatusOK, data)
	}

	// Apply middlewares in order
	finalHandler := baseHandler
	finalHandler = loggingmiddleware.Handle(finalHandler)

	return finalHandler
}

func wrapSessionControllerCompareSessionInstances(handler *SessionController) echo.HandlerFunc {
	return func(c echo.Context) error {

		err := handler.CompareSessionInstances(c)
		if err != nil {
			return err
		}
		return nil
	}
}

// RegisterRoutes registers all HTTP routes with the Echo instance
func RegisterRoutes(e *echo.Echo, usercontroller *UserController, healthcontroller *HealthController, productcontroller *ProductController, sessioncontroller *SessionController, authmiddleware *AuthMiddleware, loggingmiddleware *LoggingMiddleware) {
	handler_usercontrollergetallusers := wrapUserControllerGetAllUsers(usercontroller)
	e.GET("/users", handler_usercontrollergetallusers)
	axon.DefaultRouteRegistry.RegisterRoute(axon.RouteInfo{
		Method:              "GET",
		Path:                "/users",
		EchoPath:            "/users",
		HandlerName:         "GetAllUsers",
		ControllerName:      "UserController",
		PackageName:         "controllers",
		Middlewares:         []string{},
		MiddlewareInstances: []axon.MiddlewareInstance{},
		ParameterTypes:      map[string]string{},
		Handler:             handler_usercontrollergetallusers,
	})
	handler_usercontrollergetuser := wrapUserControllerGetUser(usercontroller)
	e.GET("/users/:id", handler_usercontrollergetuser)
	axon.DefaultRouteRegistry.RegisterRoute(axon.RouteInfo{
		Method:              "GET",
		Path:                "/users/{id:int}",
		EchoPath:            "/users/:id",
		HandlerName:         "GetUser",
		ControllerName:      "UserController",
		PackageName:         "controllers",
		Middlewares:         []string{},
		MiddlewareInstances: []axon.MiddlewareInstance{},
		ParameterTypes:      map[string]string{"id": "int"},
		Handler:             handler_usercontrollergetuser,
	})
	handler_usercontrollercreateuser := wrapUserControllerCreateUser(usercontroller, authmiddleware)
	e.POST("/users", handler_usercontrollercreateuser)
	axon.DefaultRouteRegistry.RegisterRoute(axon.RouteInfo{
		Method:              "POST",
		Path:                "/users",
		EchoPath:            "/users",
		HandlerName:         "CreateUser",
		ControllerName:      "UserController",
		PackageName:         "controllers",
		Middlewares:         []string{"AuthMiddleware"},
		MiddlewareInstances: []axon.MiddlewareInstance{{
			Name:     "AuthMiddleware",
			Handler:  authmiddleware.Handle,
			Instance: authmiddleware,
		}},
		ParameterTypes:      map[string]string{},
		Handler:             handler_usercontrollercreateuser,
	})
	handler_usercontrollerupdateuser := wrapUserControllerUpdateUser(usercontroller, authmiddleware)
	e.PUT("/users/:id", handler_usercontrollerupdateuser)
	axon.DefaultRouteRegistry.RegisterRoute(axon.RouteInfo{
		Method:              "PUT",
		Path:                "/users/{id:int}",
		EchoPath:            "/users/:id",
		HandlerName:         "UpdateUser",
		ControllerName:      "UserController",
		PackageName:         "controllers",
		Middlewares:         []string{"AuthMiddleware"},
		MiddlewareInstances: []axon.MiddlewareInstance{{
			Name:     "AuthMiddleware",
			Handler:  authmiddleware.Handle,
			Instance: authmiddleware,
		}},
		ParameterTypes:      map[string]string{"id": "int"},
		Handler:             handler_usercontrollerupdateuser,
	})
	handler_usercontrollerdeleteuser := wrapUserControllerDeleteUser(usercontroller, authmiddleware)
	e.DELETE("/users/:id", handler_usercontrollerdeleteuser)
	axon.DefaultRouteRegistry.RegisterRoute(axon.RouteInfo{
		Method:              "DELETE",
		Path:                "/users/{id:int}",
		EchoPath:            "/users/:id",
		HandlerName:         "DeleteUser",
		ControllerName:      "UserController",
		PackageName:         "controllers",
		Middlewares:         []string{"AuthMiddleware"},
		MiddlewareInstances: []axon.MiddlewareInstance{{
			Name:     "AuthMiddleware",
			Handler:  authmiddleware.Handle,
			Instance: authmiddleware,
		}},
		ParameterTypes:      map[string]string{"id": "int"},
		Handler:             handler_usercontrollerdeleteuser,
	})
	handler_healthcontrollergethealth := wrapHealthControllerGetHealth(healthcontroller)
	e.GET("/health", handler_healthcontrollergethealth)
	axon.DefaultRouteRegistry.RegisterRoute(axon.RouteInfo{
		Method:              "GET",
		Path:                "/health",
		EchoPath:            "/health",
		HandlerName:         "GetHealth",
		ControllerName:      "HealthController",
		PackageName:         "controllers",
		Middlewares:         []string{},
		MiddlewareInstances: []axon.MiddlewareInstance{},
		ParameterTypes:      map[string]string{},
		Handler:             handler_healthcontrollergethealth,
	})
	handler_healthcontrollergetreadiness := wrapHealthControllerGetReadiness(healthcontroller)
	e.GET("/ready", handler_healthcontrollergetreadiness)
	axon.DefaultRouteRegistry.RegisterRoute(axon.RouteInfo{
		Method:              "GET",
		Path:                "/ready",
		EchoPath:            "/ready",
		HandlerName:         "GetReadiness",
		ControllerName:      "HealthController",
		PackageName:         "controllers",
		Middlewares:         []string{},
		MiddlewareInstances: []axon.MiddlewareInstance{},
		ParameterTypes:      map[string]string{},
		Handler:             handler_healthcontrollergetreadiness,
	})
	handler_productcontrollergetproduct := wrapProductControllerGetProduct(productcontroller)
	e.GET("/products/:id", handler_productcontrollergetproduct)
	axon.DefaultRouteRegistry.RegisterRoute(axon.RouteInfo{
		Method:              "GET",
		Path:                "/products/{id:UUID}",
		EchoPath:            "/products/:id",
		HandlerName:         "GetProduct",
		ControllerName:      "ProductController",
		PackageName:         "controllers",
		Middlewares:         []string{},
		MiddlewareInstances: []axon.MiddlewareInstance{},
		ParameterTypes:      map[string]string{"id": "uuid.UUID"},
		Handler:             handler_productcontrollergetproduct,
	})
	handler_productcontrollergetproductbycode := wrapProductControllerGetProductByCode(productcontroller, loggingmiddleware)
	e.GET("/products/by-code/:code", handler_productcontrollergetproductbycode)
	axon.DefaultRouteRegistry.RegisterRoute(axon.RouteInfo{
		Method:              "GET",
		Path:                "/products/by-code/{code:ProductCode}",
		EchoPath:            "/products/by-code/:code",
		HandlerName:         "GetProductByCode",
		ControllerName:      "ProductController",
		PackageName:         "controllers",
		Middlewares:         []string{"LoggingMiddleware"},
		MiddlewareInstances: []axon.MiddlewareInstance{{
			Name:     "LoggingMiddleware",
			Handler:  loggingmiddleware.Handle,
			Instance: loggingmiddleware,
		}},
		ParameterTypes:      map[string]string{"code": "ProductCode"},
		Handler:             handler_productcontrollergetproductbycode,
	})
	handler_productcontrollergetproductsales := wrapProductControllerGetProductSales(productcontroller, authmiddleware, loggingmiddleware)
	e.GET("/products/sales/:dateRange", handler_productcontrollergetproductsales)
	axon.DefaultRouteRegistry.RegisterRoute(axon.RouteInfo{
		Method:              "GET",
		Path:                "/products/sales/{dateRange:DateRange}",
		EchoPath:            "/products/sales/:dateRange",
		HandlerName:         "GetProductSales",
		ControllerName:      "ProductController",
		PackageName:         "controllers",
		Middlewares:         []string{"AuthMiddleware", "LoggingMiddleware"},
		MiddlewareInstances: []axon.MiddlewareInstance{{
			Name:     "AuthMiddleware",
			Handler:  authmiddleware.Handle,
			Instance: authmiddleware,
		}, {
			Name:     "LoggingMiddleware",
			Handler:  loggingmiddleware.Handle,
			Instance: loggingmiddleware,
		}},
		ParameterTypes:      map[string]string{"dateRange": "DateRange"},
		Handler:             handler_productcontrollergetproductsales,
	})
	handler_productcontrollercreateproductincategory := wrapProductControllerCreateProductInCategory(productcontroller, authmiddleware)
	e.POST("/products/:categoryId/items", handler_productcontrollercreateproductincategory)
	axon.DefaultRouteRegistry.RegisterRoute(axon.RouteInfo{
		Method:              "POST",
		Path:                "/products/{categoryId:UUID}/items",
		EchoPath:            "/products/:categoryId/items",
		HandlerName:         "CreateProductInCategory",
		ControllerName:      "ProductController",
		PackageName:         "controllers",
		Middlewares:         []string{"AuthMiddleware"},
		MiddlewareInstances: []axon.MiddlewareInstance{{
			Name:     "AuthMiddleware",
			Handler:  authmiddleware.Handle,
			Instance: authmiddleware,
		}},
		ParameterTypes:      map[string]string{"categoryId": "uuid.UUID"},
		Handler:             handler_productcontrollercreateproductincategory,
	})
	handler_productcontrollerupdateproduct := wrapProductControllerUpdateProduct(productcontroller)
	e.PUT("/products/:id", handler_productcontrollerupdateproduct)
	axon.DefaultRouteRegistry.RegisterRoute(axon.RouteInfo{
		Method:              "PUT",
		Path:                "/products/{id:UUID}",
		EchoPath:            "/products/:id",
		HandlerName:         "UpdateProduct",
		ControllerName:      "ProductController",
		PackageName:         "controllers",
		Middlewares:         []string{},
		MiddlewareInstances: []axon.MiddlewareInstance{},
		ParameterTypes:      map[string]string{"id": "uuid.UUID"},
		Handler:             handler_productcontrollerupdateproduct,
	})
	handler_productcontrollerdeleteproduct := wrapProductControllerDeleteProduct(productcontroller)
	e.DELETE("/products/:id", handler_productcontrollerdeleteproduct)
	axon.DefaultRouteRegistry.RegisterRoute(axon.RouteInfo{
		Method:              "DELETE",
		Path:                "/products/{id:UUID}",
		EchoPath:            "/products/:id",
		HandlerName:         "DeleteProduct",
		ControllerName:      "ProductController",
		PackageName:         "controllers",
		Middlewares:         []string{},
		MiddlewareInstances: []axon.MiddlewareInstance{},
		ParameterTypes:      map[string]string{"id": "uuid.UUID"},
		Handler:             handler_productcontrollerdeleteproduct,
	})
	handler_sessioncontrollerstartsession := wrapSessionControllerStartSession(sessioncontroller, loggingmiddleware)
	e.POST("/sessions/:userID", handler_sessioncontrollerstartsession)
	axon.DefaultRouteRegistry.RegisterRoute(axon.RouteInfo{
		Method:              "POST",
		Path:                "/sessions/{userID:int}",
		EchoPath:            "/sessions/:userID",
		HandlerName:         "StartSession",
		ControllerName:      "SessionController",
		PackageName:         "controllers",
		Middlewares:         []string{"LoggingMiddleware"},
		MiddlewareInstances: []axon.MiddlewareInstance{{
			Name:     "LoggingMiddleware",
			Handler:  loggingmiddleware.Handle,
			Instance: loggingmiddleware,
		}},
		ParameterTypes:      map[string]string{"userID": "int"},
		Handler:             handler_sessioncontrollerstartsession,
	})
	handler_sessioncontrollergetsessioninfo := wrapSessionControllerGetSessionInfo(sessioncontroller, loggingmiddleware)
	e.GET("/sessions/info/:userID", handler_sessioncontrollergetsessioninfo)
	axon.DefaultRouteRegistry.RegisterRoute(axon.RouteInfo{
		Method:              "GET",
		Path:                "/sessions/info/{userID:int}",
		EchoPath:            "/sessions/info/:userID",
		HandlerName:         "GetSessionInfo",
		ControllerName:      "SessionController",
		PackageName:         "controllers",
		Middlewares:         []string{"LoggingMiddleware"},
		MiddlewareInstances: []axon.MiddlewareInstance{{
			Name:     "LoggingMiddleware",
			Handler:  loggingmiddleware.Handle,
			Instance: loggingmiddleware,
		}},
		ParameterTypes:      map[string]string{"userID": "int"},
		Handler:             handler_sessioncontrollergetsessioninfo,
	})
	handler_sessioncontrollercomparesessioninstances := wrapSessionControllerCompareSessionInstances(sessioncontroller)
	e.GET("/sessions/compare", handler_sessioncontrollercomparesessioninstances)
	axon.DefaultRouteRegistry.RegisterRoute(axon.RouteInfo{
		Method:              "GET",
		Path:                "/sessions/compare",
		EchoPath:            "/sessions/compare",
		HandlerName:         "CompareSessionInstances",
		ControllerName:      "SessionController",
		PackageName:         "controllers",
		Middlewares:         []string{},
		MiddlewareInstances: []axon.MiddlewareInstance{},
		ParameterTypes:      map[string]string{},
		Handler:             handler_sessioncontrollercomparesessioninstances,
	})
}

// AutogenModule provides all controllers and route registration in this package
var AutogenModule = fx.Module("controllers",
	fx.Provide(NewUserController),
	fx.Provide(NewHealthController),
	fx.Provide(NewProductController),
	fx.Provide(NewSessionController),
	fx.Invoke(RegisterRoutes),
)
