// Code generated by Axon framework. DO NOT EDIT.
// This file was automatically generated and should not be modified manually.

package services

import (
	"context"
	"go.uber.org/fx"
	"github.com/toyz/axon/examples/complete-app/internal/config"
)

func NewDatabaseService(lc fx.Lifecycle, config *config.Config) *DatabaseService {
	service := &DatabaseService{
		Config: config,
	}
	
	lc.Append(fx.Hook{
		OnStart: func(ctx context.Context) error {
			return service.Start(ctx)
		},
		OnStop: func(ctx context.Context) error {
			return service.Stop(ctx)
		},
	})
	
	return service
}

func NewUserService(lc fx.Lifecycle, config *config.Config) *UserService {
	service := &UserService{
		Config: config,
	}
	
	lc.Append(fx.Hook{
		OnStart: func(ctx context.Context) error {
			return service.Start(ctx)
		},
		OnStop: func(ctx context.Context) error {
			return service.Stop(ctx)
		},
	})
	
	return service
}

// AutogenModule provides all core services in this package
var AutogenModule = fx.Module("services",
	fx.Provide(NewDatabaseService),
	fx.Provide(NewUserService),
)
