// Code generated by Axon framework. DO NOT EDIT.
// This file was automatically generated and should not be modified manually.

package interfaces

import (
	"go.uber.org/fx"
	"github.com/toyz/axon/internal/models"
)

func NewUserRepository() *UserRepository {
	return &UserRepository{
		storage: make(map[int]*models.User),
	}
}

// AutogenModule provides all core services in this package
var AutogenModule = fx.Module("interfaces",
	fx.Provide(NewUserRepository),
)
