// Code generated by Axon framework. DO NOT EDIT.
// This file was automatically generated and should not be modified manually.

package middleware

import (
	"github.com/labstack/echo/v4"
	"github.com/toyz/axon/examples/complete-app/internal/config"
	"github.com/toyz/axon/examples/complete-app/internal/logging"
	"github.com/toyz/axon/examples/complete-app/internal/services"
	"github.com/toyz/axon/pkg/axon"
	"go.uber.org/fx"
)

func NewLoggingMiddleware() *LoggingMiddleware {
	return &LoggingMiddleware{
	}
}
func NewAuthMiddleware(sessionFactory func() *services.SessionService, Config *config.Config) *AuthMiddleware {
	return &AuthMiddleware{
		sessionFactory: sessionFactory,
		Config: Config,
	}
}
func NewGlobalMiddleware(logger *logging.AppLogger) *GlobalMiddleware {
	return &GlobalMiddleware{
		logger: logger,
	}
}
// RegisterMiddlewares registers all middleware with the axon middleware registry
func RegisterMiddlewares(LoggingMiddleware *LoggingMiddleware, AuthMiddleware *AuthMiddleware, GlobalMiddleware *GlobalMiddleware) {
	axon.RegisterMiddlewareHandler("LoggingMiddleware", LoggingMiddleware)
	axon.RegisterMiddlewareHandler("AuthMiddleware", AuthMiddleware)
	axon.RegisterMiddlewareHandler("GlobalMiddleware", GlobalMiddleware)
}
// RegisterGlobalMiddleware registers all global middleware with Echo
func RegisterGlobalMiddleware(e *echo.Echo, GlobalMiddleware *GlobalMiddleware) {
	e.Use(GlobalMiddleware.Handle)
}
// AutogenModule provides all middleware in this package
var AutogenModule = fx.Module("middleware",
	fx.Provide(NewLoggingMiddleware),
	fx.Provide(NewAuthMiddleware),
	fx.Provide(NewGlobalMiddleware),
	fx.Invoke(RegisterMiddlewares),
	fx.Invoke(RegisterGlobalMiddleware),
)
