// Code generated by Axon framework. DO NOT EDIT.
// This file was automatically generated and should not be modified manually.

package middleware

import (
	"go.uber.org/fx"
	"github.com/toyz/axon/pkg/axon"
)

func NewAuthMiddleware() *AuthMiddleware {
	return &AuthMiddleware{}
}
func NewLoggingMiddleware() *LoggingMiddleware {
	return &LoggingMiddleware{}
}
func RegisterMiddlewares(authmiddleware *AuthMiddleware, loggingmiddleware *LoggingMiddleware) {
	axon.RegisterMiddleware("AuthMiddleware", authmiddleware.Handle, authmiddleware)
	axon.RegisterMiddleware("LoggingMiddleware", loggingmiddleware.Handle, loggingmiddleware)
}

// AutogenModule provides all middleware in this package
var AutogenModule = fx.Module("middleware",
	fx.Provide(NewAuthMiddleware),
	fx.Provide(NewLoggingMiddleware),
	fx.Invoke(RegisterMiddlewares),
)
