// Code generated by Axon framework. DO NOT EDIT.
// This file was automatically generated and should not be modified manually.

package middleware

import (
	"go.uber.org/fx"
	"github.com/labstack/echo/v4"
	"github.com/toyz/axon/pkg/axon"

	"github.com/toyz/axon/examples/complete-app/internal/config"
)

func NewAuthMiddleware(Config *config.Config) *AuthMiddleware {
	return &AuthMiddleware{
		Config: Config,
	}
}
func NewGlobalMiddleware() *GlobalMiddleware {
	return &GlobalMiddleware{
	}
}
func NewLoggingMiddleware() *LoggingMiddleware {
	return &LoggingMiddleware{
	}
}
// RegisterMiddlewares registers all middleware with the axon middleware registry
func RegisterMiddlewares(AuthMiddleware *AuthMiddleware, GlobalMiddleware *GlobalMiddleware, LoggingMiddleware *LoggingMiddleware) {
	axon.RegisterMiddlewareHandler("AuthMiddleware", AuthMiddleware)
	axon.RegisterMiddlewareHandler("GlobalMiddleware", GlobalMiddleware)
	axon.RegisterMiddlewareHandler("LoggingMiddleware", LoggingMiddleware)
}
// RegisterGlobalMiddleware registers all global middleware with Echo
func RegisterGlobalMiddleware(e *echo.Echo, GlobalMiddleware *GlobalMiddleware) {
	e.Use(GlobalMiddleware.Handle)
}
// AutogenModule provides all middleware in this package
var AutogenModule = fx.Module("middleware",
	fx.Provide(NewAuthMiddleware),
	fx.Provide(NewGlobalMiddleware),
	fx.Provide(NewLoggingMiddleware),
	fx.Invoke(RegisterMiddlewares),
	fx.Invoke(RegisterGlobalMiddleware),
)
